# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/artui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#修改783行

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_home(object):
    def setupUi(self, home):
        print("home.setObjectName=",home.setObjectName)
        home.setObjectName("home")
        home.resize(1024, 768)
        home.setMinimumSize(QtCore.QSize(1024, 768))
        home.setMaximumSize(QtCore.QSize(1024, 768))
        self.frame = QtWidgets.QFrame(home)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1024, 768))
        self.frame.setMaximumSize(QtCore.QSize(1024, 768))
        self.frame.setStyleSheet("#frame{\n"
"    border-radius:10px;\n"
"}\n"
"QFrame{\n"
"background-color: rgb(33, 34, 52);}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
" }\n"
" QTabBar::tab:first{\n"
"        margin-left: 250px;\n"
" }\n"
"QTabBar::tab {\n"
"     width: 150px;\n"
"     height:40px;\n"
"     padding-left: 10px;\n"
"     color: white;\n"
"     font: 20px;\n"
"     border: 0px solid;\n"
"  }\n"
"QTabBar::tab:selected {\n"
"         width: 150px;\n"
"         height: 40px;\n"
"         border-bottom: 2px solid #225f9a;\n"
"         background-color: #343761;\n"
"}\n"
"background-color: rgb(48, 51, 90);")
        self.tabWidget.setIconSize(QtCore.QSize(32, 32))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1021, 721))
        self.frame_2.setMinimumSize(QtCore.QSize(1021, 681))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setStyleSheet("background-color: rgb(33, 34, 52);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 25, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.frame_2)
        self.widget.setStyleSheet("background-color: rgb(33, 34, 52);")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("background-color: rgb(33, 34, 52);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_2 = QtWidgets.QWidget(self.frame_3)
        self.widget_2.setStyleSheet("background-color: rgb(33, 34, 52);")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(16)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.graph = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.graph.sizePolicy().hasHeightForWidth())
        self.graph.setSizePolicy(sizePolicy)
        self.graph.setStyleSheet("background-color: rgb(180, 183, 200);")
        self.graph.setObjectName("graph")
        self.verticalLayout_4.addWidget(self.graph)
        self.frame_5 = QtWidgets.QFrame(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("background-color: rgb(33, 34, 52);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setGeometry(QtCore.QRect(10, 10, 181, 16))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.widget_4 = QtWidgets.QWidget(self.frame_5)
        self.widget_4.setGeometry(QtCore.QRect(0, 41, 241, 331))
        self.widget_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.widget_4)
        self.textBrowser.setStyleSheet("background-color: rgb(180, 183, 200);")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.verticalLayout_6.addWidget(self.widget_2)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("background-color: rgb(33, 34, 52);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_4)
        self.stackedWidget.setStyleSheet("background-color: rgb(33, 34, 52);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_5 = QtWidgets.QWidget(self.page)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox = QtWidgets.QGroupBox(self.widget_5)
        self.groupBox.setStyleSheet("QGroupBox{\n"
"     border: 0px solid;                                    \n"
"    background-color: rgb(33, 34, 52);\n"
" }\n"
" QLabel{\n"
"  background-color: rgb(0,0,0,0);\n"
"   color: white;\n"
"    font-size:10pt;\n"
" }\n"
" #showc1,#showc2,#showc3,#showc4 {        \n"
"    background-color: rgb(83, 83, 83);\n"
"  }\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(9, 9, 9, -1)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.camera3 = QtWidgets.QWidget(self.groupBox)
        self.camera3.setStyleSheet("")
        self.camera3.setObjectName("camera3")
        self.showc3 = QtWidgets.QLabel(self.camera3)
        self.showc3.setGeometry(QtCore.QRect(0, -16, 366, 311))
        self.showc3.setStyleSheet("#showc3 {        \n"
"    background-color: rgb(83, 83, 83);\n"
"  }")
        self.showc3.setText("")
        self.showc3.setObjectName("showc3")
        self.camera3_time = QtWidgets.QLabel(self.camera3)
        self.camera3_time.setGeometry(QtCore.QRect(10, 10, 351, 16))
        self.camera3_time.setStyleSheet("")
        self.camera3_time.setObjectName("camera3_time")
        self.status_c1_3 = QtWidgets.QLabel(self.camera3)
        self.status_c1_3.setGeometry(QtCore.QRect(140, 130, 71, 21))
        self.status_c1_3.setStyleSheet("")
        self.status_c1_3.setObjectName("status_c1_3")
        self.c1_3 = QtWidgets.QLabel(self.camera3)
        self.c1_3.setGeometry(QtCore.QRect(10, 260, 71, 21))
        self.c1_3.setStyleSheet("")
        self.c1_3.setObjectName("c1_3")
        self.gridLayout.addWidget(self.camera3, 1, 0, 1, 1)
        self.camera1 = QtWidgets.QWidget(self.groupBox)
        self.camera1.setStyleSheet("")
        self.camera1.setObjectName("camera1")
        self.showc1 = QtWidgets.QLabel(self.camera1)
        self.showc1.setGeometry(QtCore.QRect(0, 0, 366, 296))
        self.showc1.setText("")
        self.showc1.setObjectName("showc1")
        self.camera1_time = QtWidgets.QLabel(self.camera1)
        self.camera1_time.setGeometry(QtCore.QRect(10, 10, 351, 16))
        self.camera1_time.setStyleSheet("")
        self.camera1_time.setObjectName("camera1_time")
        self.status_c1 = QtWidgets.QLabel(self.camera1)
        self.status_c1.setGeometry(QtCore.QRect(150, 130, 71, 16))
        self.status_c1.setStyleSheet("")
        self.status_c1.setObjectName("status_c1")
        self.c1 = QtWidgets.QLabel(self.camera1)
        self.c1.setGeometry(QtCore.QRect(10, 260, 71, 21))
        self.c1.setStyleSheet("")
        self.c1.setObjectName("c1")
        self.gridLayout.addWidget(self.camera1, 0, 0, 1, 1)
        self.camera4 = QtWidgets.QWidget(self.groupBox)
        self.camera4.setStyleSheet("")
        self.camera4.setObjectName("camera4")
        self.showc4 = QtWidgets.QLabel(self.camera4)
        self.showc4.setGeometry(QtCore.QRect(0, 0, 365, 295))
        self.showc4.setStyleSheet("")
        self.showc4.setText("")
        self.showc4.setObjectName("showc4")
        self.camera4_time = QtWidgets.QLabel(self.camera4)
        self.camera4_time.setGeometry(QtCore.QRect(10, 10, 351, 16))
        self.camera4_time.setStyleSheet("")
        self.camera4_time.setObjectName("camera4_time")
        self.status_c1_4 = QtWidgets.QLabel(self.camera4)
        self.status_c1_4.setGeometry(QtCore.QRect(150, 130, 91, 21))
        self.status_c1_4.setStyleSheet("")
        self.status_c1_4.setObjectName("status_c1_4")
        self.c1_4 = QtWidgets.QLabel(self.camera4)
        self.c1_4.setGeometry(QtCore.QRect(10, 260, 71, 21))
        self.c1_4.setStyleSheet("")
        self.c1_4.setObjectName("c1_4")
        self.gridLayout.addWidget(self.camera4, 1, 1, 1, 1)
        self.camera2 = QtWidgets.QWidget(self.groupBox)
        self.camera2.setStyleSheet(" #showc2 {        \n"
"    background-color: rgb(83, 83, 83);\n"
"     }")
        self.camera2.setObjectName("camera2")
        self.showc2 = QtWidgets.QLabel(self.camera2)
        self.showc2.setGeometry(QtCore.QRect(0, 0, 365, 296))
        self.showc2.setText("")
        self.showc2.setObjectName("showc2")
        self.camera2_time = QtWidgets.QLabel(self.camera2)
        self.camera2_time.setGeometry(QtCore.QRect(10, 10, 351, 16))
        self.camera2_time.setStyleSheet("color: rgb(255, 255, 255);")
        self.camera2_time.setObjectName("camera2_time")
        self.status_c1_2 = QtWidgets.QLabel(self.camera2)
        self.status_c1_2.setGeometry(QtCore.QRect(150, 125, 71, 21))
        self.status_c1_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.status_c1_2.setObjectName("status_c1_2")
        self.c1_2 = QtWidgets.QLabel(self.camera2)
        self.c1_2.setGeometry(QtCore.QRect(10, 260, 71, 21))
        self.c1_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.c1_2.setObjectName("c1_2")
        self.gridLayout.addWidget(self.camera2, 0, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.verticalLayout_8.addWidget(self.widget_5)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.widget_3 = QtWidgets.QWidget(self.page_2)
        self.widget_3.setGeometry(QtCore.QRect(-1, -1, 781, 611))
        self.widget_3.setObjectName("widget_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget_3)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 10, 741, 541))
        self.groupBox_4.setStyleSheet("QGroupBox{\n"
"     border: 0px solid;                                    \n"
"    background-color: rgb(33, 34, 52);\n"
" }\n"
"QLabel{\n"
" background-color: rgb(0,0,0,0);\n"
"   font: 20px;\n"
"    color: white;\n"
" }                     \n"
" #show_big_video {        \n"
"    background-color: rgb(83, 83, 83);\n"
"  }\n"
"")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Video = QtWidgets.QWidget(self.groupBox_4)
        self.Video.setStyleSheet("")
        self.Video.setObjectName("Video")
        self.show_big_video = QtWidgets.QLabel(self.Video)
        self.show_big_video.setGeometry(QtCore.QRect(0, 0, 741, 531))
        self.show_big_video.setStyleSheet("")
        self.show_big_video.setText("")
        self.show_big_video.setObjectName("show_big_video")
        self.big_time = QtWidgets.QLabel(self.Video)
        self.big_time.setGeometry(QtCore.QRect(230, 10, 401, 31))
        self.big_time.setStyleSheet("")
        self.big_time.setObjectName("big_time")
        self.big_status = QtWidgets.QLabel(self.Video)
        self.big_status.setGeometry(QtCore.QRect(350, 230, 81, 31))
        self.big_status.setStyleSheet("")
        self.big_status.setObjectName("big_status")
        self.camera_name = QtWidgets.QLabel(self.Video)
        self.camera_name.setGeometry(QtCore.QRect(10, 500, 121, 21))
        self.camera_name.setObjectName("camera_name")
        self.verticalLayout_5.addWidget(self.Video)
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget_3)
        self.groupBox_5.setGeometry(QtCore.QRect(110, 560, 551, 41))
        self.groupBox_5.setStyleSheet("border:none;")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 10, 41, 21))
        self.pushButton_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(70, 72, 93);\n"
"border-radius:5px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_4.setGeometry(QtCore.QRect(240, 10, 41, 21))
        self.pushButton_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(70, 72, 93);\n"
"border-radius:5px;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_5.setGeometry(QtCore.QRect(290, 10, 41, 21))
        self.pushButton_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(70, 72, 93);\n"
"border-radius:5px;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_7.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.widget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res\\icon/monitor_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_6 = QtWidgets.QFrame(self.tab_2)
        self.frame_6.setGeometry(QtCore.QRect(-1, -1, 1021, 721))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setGeometry(QtCore.QRect(99, -1, 811, 711))
        self.frame_8.setStyleSheet("QFrame {\n"
"    border-radius:10px;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_10.setSpacing(25)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setStyleSheet("background-color: rgb(122, 122, 122);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.parameter = QtWidgets.QTableWidget(self.frame_10)
        self.parameter.setGeometry(QtCore.QRect(20, 20, 735, 216))
        self.parameter.setStyleSheet("QTableWidget{\n"
"  background-color: #212234;\n"
"border: 0px solid;   \n"
"    color: rgb(255, 255, 255);\n"
"    font-size:7.5pt;\n"
"  }\n"
" QTableWidget::item{\n"
"    padding: 5px;\n"
"     background-color: #212234;\n"
"    border-bottom: 1px solid #5b7b9a;\n"
"    border-right: 1px solid #5b7b9a;\n"
"     border-left: 1px solid #5b7b9a;\n"
"     border-top: 1px solid #5b7b9a;\n"
"  }\n"
"                                     QTableWidget::item:selected {\n"
"                                         background-color: #99CCFF;\n"
"                                     }\n"
"                                     QHeaderView::section {\n"
"padding:1;\n"
"                                         background-color: #212234;\n"
"                                    font-size: 7.5pt;\n"
"                                         border:    1px solid #5b7b9a;\n"
"                                         border-left: 1px solid;\n"
"                                         color: white;\n"
"                                     }")
        self.parameter.setObjectName("parameter")
        self.parameter.setColumnCount(4)
        self.parameter.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.parameter.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.parameter.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.parameter.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.parameter.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.parameter.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.parameter.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.parameter.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.parameter.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.parameter.setItem(3, 3, item)
        self.Submit_param = QtWidgets.QPushButton(self.frame_10)
        self.Submit_param.setGeometry(QtCore.QRect(20, 260, 71, 41))
        self.Submit_param.setStyleSheet("QWidget{\n"
"                                            background-color: #2a2c36;\n"
"    color:white;\n"
"                                        }\n"
"                                        QPushButton{\n"
"                                            width: 70px;\n"
"                                            height: 35px;\n"
"                                            margin-left: 5px;\n"
"                                           background-color: #46485d;\n"
"                                           border-radius: 5px;\n"
"                                        }\n"
"                                        QPushButton:pressed{\n"
"                                           background-color: #25273a;\n"
"                                        }")
        self.Submit_param.setObjectName("Submit_param")
        self.verticalLayout_10.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setStyleSheet("background-color: rgb(122, 122, 122);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.status = QtWidgets.QTableWidget(self.frame_11)
        self.status.setGeometry(QtCore.QRect(20, 20, 189, 221))
        self.status.setStyleSheet("QTableWidget{\n"
"  background-color: #212234;\n"
"border: 0px solid;   \n"
"    color: rgb(255, 255, 255);\n"
"    font-size:7.5pt;\n"
"  }\n"
" QTableWidget::item{\n"
"    padding: 5px;\n"
"     background-color: #212234;\n"
"    border-bottom: 1px solid #5b7b9a;\n"
"    border-right: 1px solid #5b7b9a;\n"
"     border-left: 1px solid #5b7b9a;\n"
"     border-top: 1px solid #5b7b9a;\n"
"  }\n"
"                                     QTableWidget::item:selected {\n"
"                                         background-color: #99CCFF;\n"
"                                     }\n"
"                                     QHeaderView::section {\n"
"padding:1;\n"
"                                         background-color: #212234;\n"
"                                    font-size: 7.5pt;\n"
"                                         border:    1px solid #5b7b9a;\n"
"                                         border-left: 1px solid;\n"
"                                         color: white;\n"
"                                     }")
        self.status.setObjectName("status")
        self.status.setColumnCount(1)
        self.status.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.status.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.status.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.status.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.status.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.status.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.status.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.status.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.status.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.status.setItem(3, 0, item)
        self.Submit_status = QtWidgets.QPushButton(self.frame_11)
        self.Submit_status.setGeometry(QtCore.QRect(20, 260, 71, 41))
        self.Submit_status.setStyleSheet("QWidget{\n"
"                                            background-color: #2a2c36;\n"
"    color:white;\n"
"                                        }\n"
"                                        QPushButton{\n"
"                                            width: 70px;\n"
"                                            height: 35px;\n"
"                                            margin-left: 5px;\n"
"                                           background-color: #46485d;\n"
"                                           border-radius: 5px;\n"
"                                        }\n"
"                                        QPushButton:pressed{\n"
"                                           background-color: #25273a;\n"
"                                        }")
        self.Submit_status.setObjectName("Submit_status")
        self.verticalLayout_10.addWidget(self.frame_11)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res\\icon/camera_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon1, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.frame_7 = QtWidgets.QFrame(self.tab_3)
        self.frame_7.setGeometry(QtCore.QRect(-1, -1, 1021, 681))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setGeometry(QtCore.QRect(10, 40, 101, 141))
        self.frame_9.setStyleSheet("\n"
" QPushButton{\n"
"        width: 70px;\n"
"        height: 35px;\n"
"        margin-left: 5px;\n"
"        background-color: white;\n"
"        border-radius: 5px;\n"
" }\n"
"QPushButton:pressed{\n"
"   background-color: #25273a;\n"
"   }")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.logs = QtWidgets.QPushButton(self.frame_9)
        self.logs.setGeometry(QtCore.QRect(10, 0, 81, 51))
        self.logs.setObjectName("logs")
        self.errors = QtWidgets.QPushButton(self.frame_9)
        self.errors.setGeometry(QtCore.QRect(10, 80, 81, 51))
        self.errors.setObjectName("errors")
        self.TabWidget_logs = QtWidgets.QTableWidget(self.frame_7)
        self.TabWidget_logs.setGeometry(QtCore.QRect(150, 20, 773, 491))
        self.TabWidget_logs.setStyleSheet("QTableWidget{\n"
"                                          background-color: #212234;\n"
"                                        border:none;\n"
"                                        font-size:7.5pt;\n"
"                                            }\n"
"                                            QTableWidget::item{\n"
"                                              padding: 5px;\n"
"                                              background-color: #212234;\n"
"                                              border-bottom: 1px solid #5b7b9a;\n"
"                                              border-right: 1px solid #5b7b9a;\n"
"                                              border-left: 1px solid #5b7b9a;\n"
"                                              border-top: 1px solid #5b7b9a;\n"
"                                            }\n"
"                                            QTableWidget::item:selected {\n"
"                                               background-color: #99CCFF;\n"
"                                            }\n"
"                                            QHeaderView::section {\n"
"                                                background-color: #212234;\n"
"                                                border:    1px solid #5b7b9a;\n"
"                                                border-left: 1px solid;\n"
"                                               color: white;\n"
"                                            font-size:7.5pt;\n"
"                                            }\n"
"QPushButton{\n"
"    font-size:7.5pt;\n"
"    background-color: rgb(33, 34, 52);\n"
"    color:white;\n"
"}")
        self.TabWidget_logs.setObjectName("TabWidget_logs")
        self.TabWidget_logs.setColumnCount(5)
        self.TabWidget_logs.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.TabWidget_logs.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabWidget_logs.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabWidget_logs.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabWidget_logs.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabWidget_logs.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabWidget_logs.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabWidget_logs.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabWidget_logs.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabWidget_logs.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabWidget_logs.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabWidget_logs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabWidget_logs.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabWidget_logs.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabWidget_logs.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TabWidget_logs.setHorizontalHeaderItem(4, item)
        self.frame_14 = QtWidgets.QFrame(self.frame_7)
        self.frame_14.setGeometry(QtCore.QRect(150, 580, 801, 51))
        self.frame_14.setStyleSheet("QFrame{background-color: rgb(33, 34, 52);}\n"
"QLabel{\n"
"    color:white;\n"
"    font-size:7.5pt;\n"
"}\n"
"QLineEdit{\n"
"\n"
"    background-color: rgb(33, 34, 52);\n"
"    color:white;\n"
"    font-size:7.5pt;\n"
"}\n"
"QPushButton{\n"
"    color:white;\n"
"}")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.records_label = QtWidgets.QLabel(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.records_label.sizePolicy().hasHeightForWidth())
        self.records_label.setSizePolicy(sizePolicy)
        self.records_label.setMaximumSize(QtCore.QSize(195, 31))
        self.records_label.setStyleSheet("background-color: rgb(33, 34, 52);")
        self.records_label.setObjectName("records_label")
        self.horizontalLayout_3.addWidget(self.records_label)
        self.prev_button = QtWidgets.QPushButton(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prev_button.sizePolicy().hasHeightForWidth())
        self.prev_button.setSizePolicy(sizePolicy)
        self.prev_button.setMaximumSize(QtCore.QSize(75, 24))
        self.prev_button.setStyleSheet("background-color: rgb(33, 34, 52);")
        self.prev_button.setObjectName("prev_button")
        self.horizontalLayout_3.addWidget(self.prev_button)
        self.page_label = QtWidgets.QLabel(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_label.sizePolicy().hasHeightForWidth())
        self.page_label.setSizePolicy(sizePolicy)
        self.page_label.setMaximumSize(QtCore.QSize(195, 31))
        self.page_label.setStyleSheet("background-color: rgb(33, 34, 52);")
        self.page_label.setObjectName("page_label")
        self.horizontalLayout_3.addWidget(self.page_label)
        self.next_button = QtWidgets.QPushButton(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_button.sizePolicy().hasHeightForWidth())
        self.next_button.setSizePolicy(sizePolicy)
        self.next_button.setMaximumSize(QtCore.QSize(75, 24))
        self.next_button.setStyleSheet("background-color: rgb(33, 34, 52);")
        self.next_button.setObjectName("next_button")
        self.horizontalLayout_3.addWidget(self.next_button)
        self.label_6 = QtWidgets.QLabel(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(65, 31))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.page_input = QtWidgets.QLineEdit(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_input.sizePolicy().hasHeightForWidth())
        self.page_input.setSizePolicy(sizePolicy)
        self.page_input.setMaximumSize(QtCore.QSize(65, 19))
        self.page_input.setObjectName("page_input")
        self.horizontalLayout_3.addWidget(self.page_input)
        self.confirm_button = QtWidgets.QPushButton(self.frame_14)
        self.confirm_button.setMaximumSize(QtCore.QSize(75, 23))
        self.confirm_button.setStyleSheet("background-color: rgb(33, 34, 52);\n"
"font-size:7.5pt;")
        self.confirm_button.setObjectName("confirm_button")
        self.horizontalLayout_3.addWidget(self.confirm_button)
        self.frame_13 = QtWidgets.QFrame(self.frame_7)
        self.frame_13.setGeometry(QtCore.QRect(140, 510, 301, 61))
        self.frame_13.setStyleSheet("\n"
" QPushButton{\n"
"        width: 70px;\n"
"        height: 35px;\n"
"        margin-left: 5px;\n"
"        background-color: white;\n"
"        border-radius: 5px;\n"
"       font-size:7.5pt;\n"
" }\n"
"QPushButton:pressed{\n"
"   background-color: #25273a;\n"
"   }")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.selectall = QtWidgets.QPushButton(self.frame_13)
        self.selectall.setGeometry(QtCore.QRect(10, 10, 81, 51))
        self.selectall.setObjectName("selectall")
        self.del_checked = QtWidgets.QPushButton(self.frame_13)
        self.del_checked.setGeometry(QtCore.QRect(110, 10, 81, 51))
        self.del_checked.setObjectName("del_checked")
        self.download_checked = QtWidgets.QPushButton(self.frame_13)
        self.download_checked.setGeometry(QtCore.QRect(220, 10, 81, 51))
        self.download_checked.setObjectName("download_checked")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("res\\icon/log_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.frame_12 = QtWidgets.QFrame(self.tab_4)
        self.frame_12.setGeometry(QtCore.QRect(-1, -1, 1021, 721))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.parameter_stack_holder = QtWidgets.QWidget(self.frame_12)
        self.parameter_stack_holder.setGeometry(QtCore.QRect(140, 180, 691, 380))  # 覆盖按钮下方
        self.parameter_stack_holder.setStyleSheet("background-color: rgb(48, 51, 90);")
        self.parameter_stack_holder.setObjectName("parameter_stack_holder")
        self.parameter_stack_holder_layout = QtWidgets.QVBoxLayout(self.parameter_stack_holder)
        

        self.parameter_stack = QtWidgets.QStackedWidget(self.parameter_stack_holder)
        self.parameter_stack.setObjectName("parameter_stack")
        self.parameter_stack_holder_layout.addWidget(self.parameter_stack)

         
        self.parameter_stack_holder_layout.setContentsMargins(0, 0, 0, 0)
        self.parameter_stack_holder_layout.setSpacing(0)
        self.parameter_stack_holder_layout.setObjectName("parameter_stack_holder_layout")
        self.CLOSEDOWN = QtWidgets.QToolButton(self.frame_12)
        self.CLOSEDOWN.setGeometry(QtCore.QRect(810, 590, 91, 41))
        self.CLOSEDOWN.setObjectName("CLOSEDOWN")
        self.cutter_parameter = QtWidgets.QPushButton(self.frame_12)
        self.cutter_parameter.setGeometry(QtCore.QRect(140, 80, 241, 111))
        self.cutter_parameter.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(70, 72, 93);\n"
"border-radius:5px;\n"
"")
        self.cutter_parameter.setObjectName("cutter_parameter")
        self.Camera_parameter = QtWidgets.QPushButton(self.frame_12)
        self.Camera_parameter.setGeometry(QtCore.QRect(140, 430, 241, 101))
        self.Camera_parameter.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Camera_parameter.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(70, 72, 93);\n"
"border-radius:5px;\n"
"")
        self.Camera_parameter.setObjectName("Camera_parameter")
        self.Crop_parameter = QtWidgets.QPushButton(self.frame_12)
        self.Crop_parameter.setGeometry(QtCore.QRect(140, 260, 241, 101))
        self.Crop_parameter.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(70, 72, 93);\n"
"border-radius:5px;\n"
"")
        self.Crop_parameter.setObjectName("Crop_parameter")
        self.modelBtn = QtWidgets.QPushButton(self.frame_12)
        self.modelBtn.setGeometry(QtCore.QRect(590, 430, 241, 101))
        self.modelBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(70, 72, 93);\n"
"border-radius:5px;\n"
"")
        self.modelBtn.setObjectName("modelBtn")
        self.Other_parameter = QtWidgets.QPushButton(self.frame_12)
        self.Other_parameter.setGeometry(QtCore.QRect(590, 260, 241, 101))
        self.Other_parameter.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(70, 72, 93);\n"
"border-radius:5px;\n"
"")
        self.Other_parameter.setObjectName("Other_parameter")
        self.DemoBoard_parameter = QtWidgets.QPushButton(self.frame_12)
        self.DemoBoard_parameter.setGeometry(QtCore.QRect(590, 80, 241, 111))
        self.DemoBoard_parameter.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(70, 72, 93);\n"
"border-radius:5px;\n"
"")
        self.DemoBoard_parameter.setObjectName("DemoBoard_parameter")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("res\\icon/setting_white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.groupBox_2 = QtWidgets.QGroupBox(home)
        self.groupBox_2.setGeometry(QtCore.QRect(19, 9, 221, 41))
        self.groupBox_2.setStyleSheet("border:none;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, -10, 171, 51))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font:20px;")
        self.label_2.setObjectName("label_2")
        self.groupBox_3 = QtWidgets.QGroupBox(home)
        self.groupBox_3.setGeometry(QtCore.QRect(899, 9, 111, 51))
        self.groupBox_3.setStyleSheet("border:none；")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.min_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.min_btn.setGeometry(QtCore.QRect(50, 20, 31, 20))
        self.min_btn.setStyleSheet("color: rgb(255, 255, 255);")
        self.min_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("res\\icon/Minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.min_btn.setIcon(icon4)
        self.min_btn.setObjectName("min_btn")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 21, 31, 20))
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("res\\icon/close_balck.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon5)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(home)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton_2.clicked.connect(home.close) # type: ignore
        self.min_btn.clicked.connect(home.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(home)

    def retranslateUi(self, home):
        _translate = QtCore.QCoreApplication.translate
        home.setWindowTitle(_translate("home", "Form"))
        self.label.setText(_translate("home", "控制台信息:"))
        self.camera3_time.setText(_translate("home", "年-月-日 小时：分：秒"))
        self.status_c1_3.setText(_translate("home", "无信号"))
        self.c1_3.setText(_translate("home", "camera3"))
        self.camera1_time.setText(_translate("home", "年-月-日 小时：分：秒"))
        self.status_c1.setText(_translate("home", "无信号"))
        self.c1.setText(_translate("home", "camera1"))
        self.camera4_time.setText(_translate("home", "年-月-日 小时：分：秒"))
        self.status_c1_4.setText(_translate("home", "无信号"))
        self.c1_4.setText(_translate("home", "camera4"))
        self.camera2_time.setText(_translate("home", "年-月-日 小时：分：秒"))
        self.status_c1_2.setText(_translate("home", "无信号"))
        self.c1_2.setText(_translate("home", "camera2"))
        self.big_time.setText(_translate("home", "年-月-日 小时：分：秒 星期几"))
        self.big_status.setText(_translate("home", "无信号"))
        self.camera_name.setText(_translate("home", "camera"))
        self.pushButton_3.setText(_translate("home", "前进"))
        self.pushButton_4.setText(_translate("home", "停止"))
        self.pushButton_5.setText(_translate("home", "后退"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("home", "监控大屏"))
        item = self.parameter.verticalHeaderItem(0)
        item.setText(_translate("home", "C1"))
        item = self.parameter.verticalHeaderItem(1)
        item.setText(_translate("home", "C2"))
        item = self.parameter.verticalHeaderItem(2)
        item.setText(_translate("home", "C3"))
        item = self.parameter.verticalHeaderItem(3)
        item.setText(_translate("home", "C4"))
        item = self.parameter.horizontalHeaderItem(0)
        item.setText(_translate("home", "角度"))
        item = self.parameter.horizontalHeaderItem(1)
        item.setText(_translate("home", "高度"))
        item = self.parameter.horizontalHeaderItem(2)
        item.setText(_translate("home", "型号"))
        item = self.parameter.horizontalHeaderItem(3)
        item.setText(_translate("home", "像素"))
        __sortingEnabled = self.parameter.isSortingEnabled()
        self.parameter.setSortingEnabled(False)
        item = self.parameter.item(0, 0)
        item.setText(_translate("home", "60.0"))
        item = self.parameter.item(0, 1)
        item.setText(_translate("home", "1.5"))
        item = self.parameter.item(0, 2)
        item.setText(_translate("home", "索尼"))
        item = self.parameter.item(0, 3)
        item.setText(_translate("home", "5000"))
        item = self.parameter.item(1, 0)
        item.setText(_translate("home", "60.0"))
        item = self.parameter.item(1, 1)
        item.setText(_translate("home", "1.0"))
        item = self.parameter.item(1, 2)
        item.setText(_translate("home", "三星"))
        item = self.parameter.item(1, 3)
        item.setText(_translate("home", "2亿像素"))
        item = self.parameter.item(2, 0)
        item.setText(_translate("home", "60.0"))
        item = self.parameter.item(2, 1)
        item.setText(_translate("home", "1.0"))
        item = self.parameter.item(2, 2)
        item.setText(_translate("home", "索尼"))
        item = self.parameter.item(2, 3)
        item.setText(_translate("home", "2亿像素"))
        item = self.parameter.item(3, 0)
        item.setText(_translate("home", "60.0"))
        item = self.parameter.item(3, 1)
        item.setText(_translate("home", "1.0"))
        item = self.parameter.item(3, 2)
        item.setText(_translate("home", "索尼"))
        item = self.parameter.item(3, 3)
        item.setText(_translate("home", "2亿像素"))
        self.parameter.setSortingEnabled(__sortingEnabled)
        self.Submit_param.setText(_translate("home", "submit"))
        item = self.status.verticalHeaderItem(0)
        item.setText(_translate("home", "C1"))
        item = self.status.verticalHeaderItem(1)
        item.setText(_translate("home", "C2"))
        item = self.status.verticalHeaderItem(2)
        item.setText(_translate("home", "C3"))
        item = self.status.verticalHeaderItem(3)
        item.setText(_translate("home", "C4"))
        item = self.status.horizontalHeaderItem(0)
        item.setText(_translate("home", "运行状态"))
        __sortingEnabled = self.status.isSortingEnabled()
        self.status.setSortingEnabled(False)
        item = self.status.item(0, 0)
        item.setText(_translate("home", "S"))
        item = self.status.item(1, 0)
        item.setText(_translate("home", "S"))
        item = self.status.item(2, 0)
        item.setText(_translate("home", "R"))
        item = self.status.item(3, 0)
        item.setText(_translate("home", "R"))
        self.status.setSortingEnabled(__sortingEnabled)
        self.Submit_status.setText(_translate("home", "submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("home", "摄像头管理"))
        self.logs.setText(_translate("home", "LOGS"))
        self.errors.setText(_translate("home", "ERRORS"))
        item = self.TabWidget_logs.verticalHeaderItem(0)
        item.setText(_translate("home", "o"))
        item = self.TabWidget_logs.verticalHeaderItem(1)
        item.setText(_translate("home", "o"))
        item = self.TabWidget_logs.verticalHeaderItem(2)
        item.setText(_translate("home", "o"))
        item = self.TabWidget_logs.verticalHeaderItem(3)
        item.setText(_translate("home", "o"))
        item = self.TabWidget_logs.verticalHeaderItem(4)
        item.setText(_translate("home", "o"))
        item = self.TabWidget_logs.verticalHeaderItem(5)
        item.setText(_translate("home", "o"))
        item = self.TabWidget_logs.verticalHeaderItem(6)
        item.setText(_translate("home", "o"))
        item = self.TabWidget_logs.verticalHeaderItem(7)
        item.setText(_translate("home", "o"))
        item = self.TabWidget_logs.verticalHeaderItem(8)
        item.setText(_translate("home", "o"))
        item = self.TabWidget_logs.verticalHeaderItem(9)
        item.setText(_translate("home", "o"))
        item = self.TabWidget_logs.horizontalHeaderItem(0)
        item.setText(_translate("home", "选择"))
        item = self.TabWidget_logs.horizontalHeaderItem(1)
        item.setText(_translate("home", "序号"))
        item = self.TabWidget_logs.horizontalHeaderItem(2)
        item.setText(_translate("home", "名称"))
        item = self.TabWidget_logs.horizontalHeaderItem(3)
        item.setText(_translate("home", "时间"))
        item = self.TabWidget_logs.horizontalHeaderItem(4)
        item.setText(_translate("home", "操作"))
        self.records_label.setText(_translate("home", "共 条记录"))
        self.prev_button.setText(_translate("home", "◁"))
        self.page_label.setText(_translate("home", "当前第 1  页,共 1  页"))
        self.next_button.setText(_translate("home", "▷"))
        self.label_6.setText(_translate("home", "转至"))
        self.confirm_button.setText(_translate("home", "确认"))
        self.selectall.setText(_translate("home", "全选"))
        self.del_checked.setText(_translate("home", "删除选中"))
        self.download_checked.setText(_translate("home", "下载选中"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("home", "日志查询"))
        self.CLOSEDOWN.setText(_translate("home", "关机"))
        self.cutter_parameter.setText(_translate("home", "设置刀具参数"))
        self.Camera_parameter.setText(_translate("home", "设置摄像头参数"))
        self.Crop_parameter.setText(_translate("home", "设置作物参数"))
        self.modelBtn.setText(_translate("home", "选择模型"))
        self.Other_parameter.setText(_translate("home", "设置其它参数"))
        self.DemoBoard_parameter.setText(_translate("home", "设置开发板及视觉系统参数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("home", "系统设置"))
        self.label_2.setText(_translate("home", "苗行智能识别系统"))
        

    def set_system_name(self,system_name):
        _translate = QtCore.QCoreApplication.translate
        self.label_2.setText(_translate("home", system_name)) #"苗行智能识别系统"