from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(928, 666)
        Form.setStyleSheet("​\n"
"QSlider::handle:horizontal{ /**设置滑块样式**/\n"
"    width:8px;\n"
"    background-color:rgb(255, 253, 252);\n"
"    margin:-11px 0px -11px 0px;\n"
"    border-radius:3px;\n"
"}\n"
"QSlider::groove:horizontal{\n"
"    height:2px;\n"
"    background-color:rgb(29, 70, 179);\n"
"}\n"
"QScrollBar::add-line:vertical { /**设置向下按钮**/\n"
"    background:02123e;\n"
"    border:1px solid #083863;\n"
"}\n"
"QScrollBar::sub-line:vertical { /**设置向上按钮**/\n"
"    background:02123e;\n"
"    border:1px solid #083863;\n"
"}\n"
"QSlider::add-page:horizontal{ /**设置滚动条的增加页区域**/\n"
"    background-color:rgb(29, 70, 179);\n"
"}\n"
"QSlider::sub-page:horizontal{   /**设置滚动条的减少页区域**/\n"
"    background-color:rgb(26,217,110);\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #bbb;\n"
"    background-color: #fff;\n"
"    background:#1E3E62;\n"
"    height: 10px;\n"
"    border-radius: 4px;\n"
"}\n"
" \n"
"QSlider::sub-page:horizontal {\n"
"   background: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"        stop: 0 #0078d7, stop: 1 #0063ad);\n"
"   /** border: 1px solid #777;**/\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"}\n"
" \n"
"QSlider::add-page:horizontal {\n"
"    background: #1E3E62;\n"
"   /** border: 1px solid #777;**/\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"}\n"
" \n"
"QSlider::handle:horizontal {\n"
"    /**background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #eee, stop:1 #ccc);\n"
"    border: 1px solid #777;\n"
"    width: 13px;\n"
"    margin-top: -2px;\n"
"    margin-bottom: -2px;\n"
"    border-radius: 4px;**/\n"
"}\n"
"QSlider::handle:horizontal{\n"
"    image: url(:/slices/bkpv (9).png);\n"
"    width:20px;\n"
"    height:20px;\n"
"    margin-top:-2px;\n"
"    margin-bottom:-2px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"   /** background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #fff, stop:1 #ddd);\n"
"    border: 1px solid #444;\n"
"    border-radius: 4px;**/\n"
"}\n"
"QSlider::sub-page:horizontal:disabled {\n"
"    background: #bbb;\n"
"    border-color: #999;\n"
"}\n"
"QSlider::add-page:horizontal:disabled {\n"
"    background: #eee;\n"
"    border-color: #999;\n"
"}\n"
"QSlider::handle:horizontal:disabled {\n"
"    background: #eee;\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 4px;\n"
"}\n"
" \n"
"QSlider::groove:vertical {\n"
"    border: 1px solid #bbb;\n"
"    background: white;\n"
"    width: 10px;\n"
"    border-radius: 4px;\n"
"}\n"
" \n"
"QSlider::sub-page:vertical {\n"
"    background: qlineargradient(x1: 0, y1: 1, x2: 1, y2: 1,\n"
"        stop: 0 #0078d7, stop: 1 #0063ad);\n"
"    border: 1px solid #777;\n"
"    width: 10px;\n"
"    border-radius: 4px;\n"
"}\n"
" \n"
"QSlider::add-page:vertical {\n"
"    background: #fff;\n"
"    border: 1px solid #777;\n"
"    width: 10px;\n"
"    border-radius: 4px;\n"
"}\n"
" \n"
"QSlider::handle:vertical {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #eee, stop:1 #ccc);\n"
"    border: 1px solid #777;\n"
"    height: 13px;\n"
"    margin-left: -2px;\n"
"    margin-right: -2px;\n"
"    border-radius: 4px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #fff, stop:1 #ddd);\n"
"    border: 1px solid #444;\n"
"    border-radius: 4px;\n"
"}\n"
"QSlider::sub-page:vertical:disabled {\n"
"    background: #bbb;\n"
"    border-color: #999;\n"
"}\n"
"QSlider::add-page:vertical:disabled {\n"
"    background: #eee;\n"
"    border-color: #999;\n"
"}\n"
"QSlider::handle:vertical:disabled {\n"
"    background: #eee;\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 4px;\n"
"}\n"
" \n"
"QSlider::groove:horizontal:disabled {\n"
"    background: #1E3E62;\n"
"    border-color: #999;\n"
"}")
        self.original_image = QtWidgets.QLabel(Form)
        self.original_image.setGeometry(QtCore.QRect(17, 87, 431, 361))
        self.original_image.setMaximumSize(QtCore.QSize(600, 600))
        self.original_image.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: white;\n"
"}\n"
"")
        self.original_image.setObjectName("original_image")
        self.detected_image = QtWidgets.QLabel(Form)
        self.detected_image.setGeometry(QtCore.QRect(477, 87, 431, 361))
        self.detected_image.setMaximumSize(QtCore.QSize(600, 600))
        self.detected_image.setStyleSheet("QLabel {\n"
"    background-color: white;\n"
"    color: white;\n"
"}\n"
"")
        self.detected_image.setObjectName("detected_image")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(47, -3, 841, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.picture_detect_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.picture_detect_pushButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.picture_detect_pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    background-image: url(\"./image.png\");\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #aa00ff);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}")
        self.picture_detect_pushButton.setObjectName("picture_detect_pushButton")
        self.horizontalLayout.addWidget(self.picture_detect_pushButton)
        self.video_detect_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.video_detect_pushButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.video_detect_pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    background-image: url(\"./image.png\");\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #aa00ff);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}")
        self.video_detect_pushButton.setObjectName("video_detect_pushButton")
        self.horizontalLayout.addWidget(self.video_detect_pushButton)
        self.camera_detect_pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.camera_detect_pushButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.camera_detect_pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    background-image: url(\"./image.png\");\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #aa00ff);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}")
        self.camera_detect_pushButton.setObjectName("camera_detect_pushButton")
        self.horizontalLayout.addWidget(self.camera_detect_pushButton)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(50, 490, 861, 181))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.start_detect_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.start_detect_pushButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.start_detect_pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    background-image: url(\"./image.png\");\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #aa00ff);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}")
        self.start_detect_pushButton.setObjectName("start_detect_pushButton")
        self.horizontalLayout_2.addWidget(self.start_detect_pushButton)
        self.pause_detect_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.pause_detect_pushButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pause_detect_pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    background-image: url(\"./image.png\");\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #aa00ff);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}")
        self.pause_detect_pushButton.setObjectName("pause_detect_pushButton")
        self.horizontalLayout_2.addWidget(self.pause_detect_pushButton)
        self.stop_detect_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.stop_detect_pushButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.stop_detect_pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #aa55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    background-image: url(\"./image.png\");\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
" \n"
"QPushButton:hover\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #1296db);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    color:#ffffff; /*文字颜色*/\n"
"    background-color:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop:0 #ff55ff, stop: 1 #aa00ff);/*背景色*/\n"
"    border-style:outset; /*边框风格*/\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-color:#0055ff; /*边框颜色*/\n"
"    border-radius:10px; /*边框倒角*/\n"
"    font:bold 14px; /*字体*/\n"
"    font-family: Segoe UI;\n"
"    min-width:100px;/*控件最小宽度*/\n"
"    min-height:20px;/*控件最小高度*/\n"
"    padding:4px;/*内边距*/\n"
"}")
        self.stop_detect_pushButton.setObjectName("stop_detect_pushButton")
        self.horizontalLayout_2.addWidget(self.stop_detect_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.original_image.setText(_translate("Form", "初始图片"))
        self.detected_image.setText(_translate("Form", "检测结果"))
        self.picture_detect_pushButton.setText(_translate("Form", "图片检测"))
        self.video_detect_pushButton.setText(_translate("Form", "视频检测"))
        self.camera_detect_pushButton.setText(_translate("Form", "摄像头检测"))
        self.start_detect_pushButton.setText(_translate("Form", "开始检测"))
        self.pause_detect_pushButton.setText(_translate("Form", "暂停检测"))
        self.stop_detect_pushButton.setText(_translate("Form", "结束当前检测"))
