# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\clone-crop\crop_web-client-pp\src\clientside\ui\parameter.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 905)
        Form.setStyleSheet("background-color: rgb(33, 34, 52);\n"
"")
        self.cutter_parameter = QtWidgets.QPushButton(Form)
        self.cutter_parameter.setGeometry(QtCore.QRect(110, 130, 241, 111))
        self.cutter_parameter.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(70, 72, 93);\n"
"border-radius:5px;\n"
"")
        self.cutter_parameter.setObjectName("cutter_parameter")
        self.Crop_parameter = QtWidgets.QPushButton(Form)
        self.Crop_parameter.setGeometry(QtCore.QRect(110, 310, 241, 101))
        self.Crop_parameter.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(70, 72, 93);\n"
"border-radius:5px;\n"
"")
        self.Crop_parameter.setObjectName("Crop_parameter")
        self.Other_parameter = QtWidgets.QPushButton(Form)
        self.Other_parameter.setGeometry(QtCore.QRect(560, 310, 241, 101))
        self.Other_parameter.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(70, 72, 93);\n"
"border-radius:5px;\n"
"")
        self.Other_parameter.setObjectName("Other_parameter")
        self.closeBtn = QtWidgets.QPushButton(Form)
        self.closeBtn.setGeometry(QtCore.QRect(780, 680, 111, 51))
        self.closeBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(70, 72, 93);\n"
"border-radius:5px;\n"
"")
        self.closeBtn.setObjectName("closeBtn")
        self.DemoBoard_parameter = QtWidgets.QPushButton(Form)
        self.DemoBoard_parameter.setGeometry(QtCore.QRect(560, 130, 241, 111))
        self.DemoBoard_parameter.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(70, 72, 93);\n"
"border-radius:5px;\n"
"")
        self.DemoBoard_parameter.setObjectName("DemoBoard_parameter")
        self.Camera_parameter = QtWidgets.QPushButton(Form)
        self.Camera_parameter.setGeometry(QtCore.QRect(110, 480, 241, 101))
        self.Camera_parameter.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.Camera_parameter.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(70, 72, 93);\n"
"border-radius:5px;\n"
"")
        self.Camera_parameter.setObjectName("Camera_parameter")
        self.modelBtn = QtWidgets.QPushButton(Form)
        self.modelBtn.setGeometry(QtCore.QRect(560, 480, 241, 101))
        self.modelBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(70, 72, 93);\n"
"border-radius:5px;\n"
"")
        self.modelBtn.setObjectName("modelBtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cutter_parameter.setText(_translate("Form", "设置刀具参数"))
        self.Crop_parameter.setText(_translate("Form", "设置作物参数"))
        self.Other_parameter.setText(_translate("Form", "设置其它参数"))
        self.closeBtn.setText(_translate("Form", "关闭页面"))
        self.DemoBoard_parameter.setText(_translate("Form", "设置开发板及视觉系统参数"))
        self.Camera_parameter.setText(_translate("Form", "设置摄像头参数"))
        self.modelBtn.setText(_translate("Form", "选择模型"))
